# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-29 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
