# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-03 21:47
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190203_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sumary',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Post Content'),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=ckeditor.fields.RichTextField(default='Post Summary'),
        ),
    ]
