# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20190203_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='value',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='name',
            field=models.CharField(default='User', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occurrence',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='drivers_licence',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='dut_copy',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='traffic_ticket',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
