# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-22 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20190522_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='plan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
